### ISSUE TITLE
file upload failed

### ISSUE THREAD

**Issue by Cyrille37** [redhog/ep_fileupload#20]
Hi
with EP 1.5.7 and ep_file_upload 0.0.9 a day the plugin failed to work.

In EP log file at file uploading I can read:
```
[2016-02-21 22:41:15.608] [WARN] client - Error: Permission denied to access property "document" -- { errorId: 'bVmOML9kAUQObioyna28',
  msg: 'Error: Permission denied to access property "document"',
  url: 'http://pad.example.com/p/secret_pad',
  linenumber: 454,
  userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0' }
```

**Comment by JohnMcLear** [comment]
Cross domain issue?

**Comment by Cyrille37** [comment]
clicked "update" on plugin "admin" in "plugin manager" and now file upload back at work ... mystery...

**Comment by Cyrille37** [comment]
Months later there are javascript error in browser's javascript console. Now it's clean.
I did a "nom update" and clicked on "update" button side the "admin plugin" and upload works "à novueau". mystery ...

Cheers
Cyrille
